### ISSUE TITLE
Security Audit doesnt work 

### ISSUE THREAD

**Issue by gtrossell** [LLNL/slapi#4]
Hello All, 

The security audit doesn't currently work correctly, it doesn't seem to parse the XML response correctly when checking to see if one is already running. When you turn on verbose, you can see that in the XML response is that nothing is running, but for some reason even with the 'start' parameter added it still wont run as it says one is already running.

I removed the check to see if one was running, and the command is successful, so its not a Spectra BlueScale or command structure issue, its more that the initial XML response when checking to see if one is already running isn't working.

**Comment by hawartens** [comment]
Thank you @gtrossell. Can you please include the version of BlueScale you are running?  Thanks!

**Comment by hawartens** [comment]
Also just checking what type of library you are running against (TFinity, etc).

**Comment by gtrossell** [comment]
Hi,

It's BlueScale 12.8.3 - latest code to be released this week.

TFinity 3 Frame library

George

Sent from my HUAWEI Mate 20 Pro on Three.


-------- Original message --------

**Comment by hawartens** [comment]
Thanks. Did this work for you prior to 12.8.3? I don’t currently have 12.8.3 installed anywhere. Can you please post the entire output (using the original code) with the `--verbose` option?

**Comment by hawartens** [comment]
I believe I see what happened.  Looks like in older versions of BlueScale, if an audit was not running the message looked like:
`Security audit is not running.`
With the newest BlueScale, the string has been updated to:
`Security Audit is not running.`
Our check is a bit too brittle.
Thanks for the report.

**Comment by gtrossell** [comment]
Hi Herbs,

I'm glad you where able to find the issue. Sorry I was not able to respond back sooner with the verbose output, I have been out of the office installing a Spectra unit today.

Thanks for letting me know you found the cause of the issue.

George

Sent from my HUAWEI Mate 20 Pro on Three.


-------- Original message --------

**Comment by hawartens** [comment]
Should be fixed in 0.11.1
Please let me know if you have any problems with the fix.
