### ISSUE TITLE
ciphers don't match?

### ISSUE THREAD

**Issue by rdp** [LLNL/slapi#6]
For some reason with our bluescale, the connection in chrome says `The connection to this site is encrypted and authenticated using TLS 1.2, ECDHE_RSA with P-256, and AES_128_GCM.` however when attempting to connect with slapi, I get:

`Command 'drivelist': <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)>`

Somehow the ciphers aren't lining up, as commenting out the set_ciphers line and it works.  Thank you.

**Comment by hawartens** [comment]
Interesting. Are you using a TFinity library? If not, can you please specify what library you are using? Can you please specify the version of BlueScale you are using as well? Thanks you.

**Comment by rdp** [comment]
It's a Tfinity.  Not sure on installation details.  curl -v reports this: `SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384` BlueScale12.8.03.02. Thanks!

**Comment by hawartens** [comment]
Thanks for the info. What OS are you running from? Python version? OpenSSL version? We are currently using a variant of RHEL7. I am guessing that might be the difference. When I connect using curl I get:

* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

I can see our python 3.6 ssl module is using:
openssl-libs-1.0.2k-21.el7_9.x86_64

**Comment by rdp** [comment]
Homebrew python 3

>>> ssl.OPENSSL_VERSION
'OpenSSL 1.1.1i  8 Dec 2020'

Thanks!

**Comment by hawartens** [comment]
That is very helpful! I am now able to reproduce your issue on my Mac (never tried running slapi on a Mac before).  Should have an official fix soon.

**Comment by hawartens** [comment]
Sorry it took so long, but this should be fixed!
